#%RAML 1.0

title: Finance budget
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-finance

documentation:
  - title: Budget API
    content: This documents the API calls that can be made to manage budgets

types:
  budget: !include acq-models/mod-finance/schemas/budget.json
  sharedBudget: !include acq-models/mod-finance/schemas/shared_budget.json
  budgetsCollection: !include acq-models/mod-finance/schemas/budget_collection.json
  budgetExpenseClassTotal: !include acq-models/mod-finance/schemas/budget_expense_class_totals.json
  budgetExpenseClassTotalsCollection: !include acq-models/mod-finance/schemas/budget_expense_class_totals_collection.json
  errors: !include raml-util/schemas/errors.schema
  budgetExpenseClassCollection: !include acq-models/mod-finance/schemas/budget_expense_class_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection-with-json-response.raml
  collection-item: !include raml-util/rtypes/item-collection-with-json-response.raml
  collection-get: !include raml-util/rtypes/collection-get-with-json-response.raml

/finance/budgets:
  displayName: Finance budget
  description: Finance budget APIs
  type:
    collection:
      schemaCollection: budgetsCollection
      schemaItem: sharedBudget
      exampleCollection: !include acq-models/mod-finance/examples/budget_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/shared_budget.sample
  post:
    is: [validate]
  get:
    is: [
      pageable,
      searchable: {description: "with valid searchable fields: for example code", example: "[\"name\", \"HIST-FY19\", \"=\"]"}
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a budget
        type: UUID
    displayName: Budget
    description: Get, Delete or Update a specific budget
    type:
      collection-item:
        schema: sharedBudget
        exampleItem: !include acq-models/mod-finance/examples/shared_budget.sample
    put:
      is: [validate]
    /expense-classes-totals:
      displayName: Expense classes totals
      description: Get expense classes totals within a given budget
      type:
        collection-get:
          exampleCollection: !include acq-models/mod-finance/examples/budget_expense_class_totals_collection.sample
          schemaCollection: budgetExpenseClassTotalsCollection
    /recalculate:
      displayName: Recalculate Budget
      description: Recalculate the budget based on transactions.
      post:
        is: [ validate ]
        description: Recalculate the budget
        responses:
          200:
            description: "Budget recalculated successfully"
          404:
            description: "Budget with a given ID not found"
            body:
              text/plain:
                example: "Budget not found"
              application/json:
                example:
                  strict: false
                  value: !include raml-util/examples/errors.sample
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "internal server error, contact administrator"
              application/json:
                example:
                  strict: false
                  value: !include raml-util/examples/errors.sample


