#%RAML 1.0

title: Finance fund
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-finance

documentation:
  - title: Fund API
    content: This documents the API calls that can be made to manage funds

types:
  fund: !include acq-models/mod-finance/schemas/fund.json
  fundsCollection: !include acq-models/mod-finance/schemas/fund_collection.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/finance/funds:
  displayName: Finance fund
  description: Finance fund APIs
  type:
    collection:
      schemaCollection: fundsCollection
      schemaItem: fund
      exampleCollection: !include acq-models/mod-finance/examples/fund_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/fund.sample
  post:
    is: [validate]
  get:
    is: [
      pageable,
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"}
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a fund
        type: UUID
    displayName: Fund
    description: Get, Delete or Update a specific fund
    type:
      collection-item:
        schema: fund
        exampleItem: !include acq-models/mod-finance/examples/fund.sample
    put:
      is: [validate]
