#%RAML 1.0
title: Finance - fund update logs
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-finance

documentation:
  - title: Fund update logs APIs
    content: This documents the API calls that can be made to manage fund update logs

types:
  errors: !include raml-util/schemas/errors.schema
  sequenceNumber: !include acq-models/common/schemas/sequence_number.json
  fund-update-log: !include acq-models/mod-finance/schemas/fund_update_log.json
  fund-update-log-collection: !include acq-models/mod-finance/schemas/fund_update_log_collection.json
  example-fund-update-log: !include acq-models/mod-finance/examples/fund_update_log.sample
  example-fund-update-log-collection: !include acq-models/mod-finance/examples/fund_update_log_collection.sample
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml


/finance/fund-update-logs:
  displayName: Fund update logs APIs
  description: Fund update logs
  type:
    collection:
      schemaItem: fund-update-log
      schemaCollection: fund-update-log-collection
      exampleItem: example-fund-update-log
      exampleCollection: example-fund-update-log-collection
  post:
    is: [validate]
  get:
    is: [
      searchable: {description: "with valid searchable fields: for example jobName", example: "[\"jobName\", \"fund update\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a fund update log
        type: UUID
    type:
      collection-item:
        schema: fund-update-log
        exampleItem: example-fund-update-log
    put:
      is: [validate]
