#%RAML 1.0

title: Finance ledger
version: v2
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-finance

documentation:
  - title: Ledger API
    content: This documents the API calls that can be made to manage ledgers

types:
  ledger: !include acq-models/mod-finance/schemas/ledger.json
  fiscal_year: !include acq-models/mod-finance/schemas/fiscal_year.json
  ledgersCollection: !include acq-models/mod-finance/schemas/ledger_collection.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  item-collection-get: !include raml-util/rtypes/item-collection-get.raml

/finance/ledgers:
  displayName: Finance ledger
  description: Finance ledger APIs
  type:
    collection:
      schemaCollection: ledgersCollection
      schemaItem: ledger
      exampleCollection: !include acq-models/mod-finance/examples/ledger_collection.sample
      exampleItem: !include acq-models/mod-finance/examples/ledger.sample
  post:
    is: [validate]
  get:
    is: [
      pageable,
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"}
    ]
    queryParameters:
      fiscalYear:
        description: Fiscal Year Id
        type: UUID
        required: false
        example: "3defdcde-3002-41d3-a31c-1fb88288f872"
        default: null
  /{id}:
    uriParameters:
      id:
        description: The UUID of a ledger
        type: UUID
    displayName: Ledger
    description: Get, Delete or Update a specific ledger
    type:
      collection-item:
        schema: ledger
        exampleItem: !include acq-models/mod-finance/examples/ledger.sample
    put:
      is: [validate]
    get:
      queryParameters:
        fiscalYear:
          description: The UUID of a fiscal year
          type: UUID
    /current-fiscal-year:
      displayName: Current fiscal year
      description: Get current fiscal year for a specific ledger
      type:
        item-collection-get:
          schema: fiscal_year
          exampleItem: !include acq-models/mod-finance/examples/fiscal_year.sample
