#%RAML 1.0

title: Release encumbrance
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-finance

documentation:
  - title: Release encumbrance API
    content: This documents the API calls that release any remaining money encumbered back to the budget's available pool

types:
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml

/finance/release-encumbrance/{id}:
    uriParameters:
      id:
        description: The UUID of an encumbrance
        type: UUID
    displayName: Finance release encumbrance
    description: Finance release encumbrance APIs
    post:
      is: [validate, language]
      description: Release encumbrance
      responses:
        204:
          description: "Encumbrance successfully released"
        400:
          description: "Bad request, malformed query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
          body:
            text/plain:
              example: "Transaction type is not encumbrance"
        404:
          description: "Encumbrance with a given ID not found"
          body:
            text/plain:
              example: "Encumbrance not found"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "internal server error, contact administrator"
